server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhanrq8888/DAD123.git # ruta del repositorio git
          searchPaths: config-data
          default-label: comunicacion
  security:
    user:
      name: root
      password: 123456